### ISSUE TITLE
support for other i-tags

### ISSUE THREAD

**Issue by krasi-georgiev** [jmleglise/mylittle-domoticz#3]
Really useful stuff at 
https://www.domoticz.com/wiki/Presence_detection_(Bluetooth_4.0_Low_energy_Beacon)

Where I live they only sell the beacons that are not supported
https://www.banggood.com/Sfd-p-985626.html

http://www.blueluminance.com/HM-10-as-iBeacon.pdf
I was wondering if you tried to send a wake-up signal as described in here? maybe the app send a sleep signal.

If you still have one of these around I would really appreciate it if you could make a quick test.

**Comment by jmleglise** [comment]
Hi, 

Yes, I have one device like this and yes It goes to sleep. I did not know this modus operandi to wake it
If you send me a script to test, I may give it a try in the next 10 days.

**Comment by krasi-georgiev** [comment]
I ordered one so I will test it and let you know.

**Comment by krasi-georgiev** [comment]
It works ok. Doesn't need a wake signal
